name: Rust Documentation

on:
  push:
    branches:
      - master

jobs:
  build-and-publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build documentation
        run: cargo doc --no-deps

      - name: Publish documentation
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: target/doc
