name: Rust Documentation

on:
  push:
    branches:
      - master
  pull_request:


jobs:
  build-and-publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build documentation
        run: cargo doc --no-deps

      - name: Commit documentation
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update documentation"
          add: "docs/"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: gh-pages
          directory: docs
          github_token: ${{ secrets.GITHUB_TOKEN }}
